# Generated by Django 4.1.3 on 2022-12-05 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(default=datetime.date(2022, 12, 5))),
                ('gender', models.CharField(choices=[('', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=120)),
                ('degree', models.CharField(choices=[('', 'select'), ('bca', 'BCA'), ('b-tech', 'B-Tech'), ('bsc', 'BSC'), ('other', 'OTHER')], max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
