# Generated by Django 4.1.3 on 2022-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_completed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=120),
        ),
    ]
